title: Stackbit Exto Theme
baseURL: /
params:
  color_scheme: light
  accent_color: pink
  header:
    title: NPCIO
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Services
        url: /portfolio/
        style: link
      - label: About
        url: /about/
        style: link
      - label: Contact
        url: /contact/
        style: link
    logo_img: images/Screenshot 2021-04-26 4.31.23 PM.png
  footer:
    content: '&copy; Visible Venture. All rights reserved.'
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/dkoosis'
        style: icon
        icon: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/dkoosis'
        style: icon
        icon: instagram
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/davidkoosis'
        style: icon
        icon: linkedin
        new_window: true
  domain: 'https://good-tulip-5b83c.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
